name: Docker CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout mode
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: build docker image
        run: docker build -t app:test .

      - name: Run docker container
        run: |
          docker compose up -d
          sleep 20
          curl -f http://localhost:8090/actuator/health || exit 1
          docker compose down
          
          
